# Generated by Django 5.1.7 on 2025-03-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('job', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=40)),
            ],
            options={
                'db_table': '"computer"',
            },
        ),
    ]
