# Generated by Django 5.1.7 on 2025-03-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computer',
            table='computer',
        ),
    ]
