# Generated by Django 5.1.7 on 2025-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_alter_computer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='department',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='job',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='note',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='userid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
