# Generated by Django 5.1.7 on 2025-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_alter_computer_department_alter_computer_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='buy',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='cd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='disk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='mainboard',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='screen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='vga',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
