# Generated by Django 5.1.7 on 2025-03-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_computer_buy_computer_cd_computer_cpu_computer_disk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='buy',
            field=models.IntegerField(null=True),
        ),
    ]
