# Generated by Django 5.1.7 on 2025-03-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_alter_computer_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='screen',
            new_name='monitor',
        ),
    ]
