# Generated by Django 5.1.7 on 2025-03-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0006_rename_screen_computer_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_TXTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10, null=True)),
                ('userid', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('cd', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(max_length=40, null=True)),
                ('department', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('buy', models.IntegerField(null=True)),
                ('mainboard', models.CharField(max_length=20, null=True)),
                ('cpu', models.CharField(max_length=20, null=True)),
                ('ram', models.CharField(max_length=20, null=True)),
                ('disk', models.CharField(max_length=20, null=True)),
                ('vga', models.CharField(max_length=20, null=True)),
                ('monitor', models.CharField(max_length=20, null=True)),
                ('note', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'computer_txts',
            },
        ),
    ]
